# Generated by Django 2.0.5 on 2018-10-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponBank', '0003_auto_20181011_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='posted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to='picture/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='posted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
